version: '3'

services:
  # nginx
  nginx:
    container_name: 'nginx'
    image: 'nginx:1.14'
    ports:
      - 81:80
    volumes:
      - ./backend:/srv:rw
      - ./docker/nginx/conf/site-default.conf:/etc/nginx/conf.d/default.conf
    links:
      - 'php'

  # php
  php:
    container_name: 'php'
    build: './docker/php'
    working_dir: '/srv'
    command: bash -c 'composer install && php-fpm'
    volumes:
      - './backend:/srv'

  # database
  database:
    container_name: 'database'
    build: './docker/database'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: Asia/Tokyo
    volumes:
      - ./docker/database/data:/var/lib/mysql
    ports:
      - 3306:3306
