version: '3'

services:
  # nginx
  nginx:
    container_name: 'nginx'
    image: 'nginx:1.14'
    ports:
      - 80:80
    volumes:
      - ./backend:/srv:rw
      - ./docker/nginx/conf/site-default.conf:/etc/nginx/conf.d/default.conf
    links:
      - 'php'

  # php
  php:
    container_name: 'php'
    build: './docker/php'
    working_dir: '/srv'
    command: bash -c 'composer install && php-fpm'
    volumes:
      - './backend:/srv'

  node:
    image: node:lts
    working_dir: /app
    volumes:
      - './backend:/app'
      - 'node_modules:/app/node_modules'
    command: sh -c 'npm install && npm run dev -- --host'
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 5173:5173

  # database
  database:
    container_name: 'database'
    build: './docker/database'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    volumes:
      - ./docker/database/data:/var/lib/mysql
    ports:
      - 3306:3306

  mailpit:
    image: axllent/mailpit
    ports:
      - 8025:8025

volumes:
  node_modules:
